# Services
services:
    maxmind.geoip:
        class:      Maxmind\Bundle\GeoipBundle\Service\GeoipManager
        arguments:  [%maxmind_geoip_data_file_path%, %maxmind_geoip_data_file_name%, %maxmind_geoip_language%]
